defaults:
  - _self_

# Model parameters
model:
  dim_cutoff: 6 
  wires: 3
  # layers: 1 # not implemented yet
  photon_modes: 3
  which_circuit: "new"  # "default" or "new"

# Training parameters
training:
  epochs: 20
  learning_rate: 0.005
  batch_size: 8
  loss_fn: "bce"  # "bce" or "mse"
  tanh: false

# Data parameters
data:
  train_jets: 100 # /40000
  val_jets: 20 # /10000
  test_jets: 120 # /20000
  data_dir: "/rds/general/user/lr1424/home/1P1Qm_SF/flat_train/TTBar+ZJets_flat.h5"
  val_dir: "/rds/general/user/lr1424/home/1P1Qm_SF/flat_val/TTBar+ZJets_flat.h5"
  test_dir: "/rds/general/user/lr1424/home/1P1Qm_SF/flat_test/TTBar+ZJets_flat.h5"
  save_dir: "/rds/general/user/lr1424/home/1P1Qm_SF/sf_refactor/saved_models_sf"

# Early stopping and learning rate parameters
optimization:
  patience: 3
  min_delta: 0.003
  restore_best: true
  lr_patience: 2
  lr_factor: 0.5
  min_lr: 1e-5

# Runtime parameters
runtime:
  cli_test: false
  run_name: null  # Will be set via command line or auto-generated
